#! /bin/bash

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# modules
## colors
hfsdir="$HOME/.config/herbstluftwm/scripts"
source "$hfsdir/colors";

# panel
hc spawn $hfsdir/lemonbar.sh


# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-c close_or_remove
## apps
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-w spawn luakit
hc keybind $Mod-comma spawn ~/.config/herbstluftwm/scripts/hcpad.py -i 10
hc keybind $Mod-period spawn ~/.config/herbstluftwm/scripts/hcpad.py -d 10
hc keybind $Mod-r spawn dmenu_run -i -nb "${color['black']}" \
              -nf "${color['white']}" -sb "${color['blue']}" \
              -sf "${color['black']}"

hc detect_monitors
# tags

hc set default_frame_layout 2 #default frame

TAG_NAMES=( I II III IV V )
TAG_KEYS=( {1..5}  )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Right use_index +1
hc keybind $Mod-Left  use_index -1

# layouting
hc keybind $Mod-d remove
hc keybind $Mod-p cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-f floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-minus pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 resize
hc mousebind $Mod-Button2 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle -1
hc keybind $Mod-Control-Tab cycle_all +1
hc keybind $Mod-Control-Shift-Tab cycle_all -1
#hc keybind $Mod-Shift-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# settings
hc set tree_style "╾ ╼"
hc pad 0 23 0 0 0
hc set frame_bg_transparent 1

## colors & gaps
hc set frame_border_active_color ${color["white"]}
hc set frame_border_normal_color ${color["black"]}
hc set frame_bg_normal_color ${color["black"]}
hc set frame_bg_active_color ${color["gray"]}
hc set frame_border_width 1
hc set frame_gap 10
hc set window_border_width 1
hc set window_border_normal_color ${color["black"]}
hc set window_border_active_color ${color["white"]}
hc set always_show_frame 0
hc set window_gap 0

# workarond to make default_frame_layouts work on the original frame of tags

hc split vertical 0.5; hc remove

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally *DO* focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class='Gvim' pseudotile=on
hc rule class='feh' pseudotile=on
hc rule class='Gcolor2' pseudotile=on
hc rule class='Agave' pseudotile=on
## GIMP
# use tag 9
hc load 5 '
(split horizontal:0.850000:0
  (split horizontal:0.200000:1
    (clients vertical:0)
    (clients max:0))
  (clients vertical:0))
'                         #load predefined layout
# center all other gimp windows on tag 9
hc rule class=Gimp tag=9 index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
  pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

